# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timetable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'timetable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftimetable.proto\x12\ttimetable\"\'\n\tTimeRange\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\"h\n\x0c\x43heckRequest\x12\'\n\tcandidate\x18\x01 \x01(\x0b\x32\x14.timetable.TimeRange\x12/\n\x11\x65xisting_bookings\x18\x02 \x03(\x0b\x32\x14.timetable.TimeRange\"?\n\rCheckResponse\x12\x14\n\x0chas_conflict\x18\x01 \x01(\x08\x12\x18\n\x10\x63onflict_details\x18\x02 \x01(\t2Z\n\x10TimetableChecker\x12\x46\n\x11\x43heckAvailability\x12\x17.timetable.CheckRequest\x1a\x18.timetable.CheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timetable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMERANGE']._serialized_start=30
  _globals['_TIMERANGE']._serialized_end=69
  _globals['_CHECKREQUEST']._serialized_start=71
  _globals['_CHECKREQUEST']._serialized_end=175
  _globals['_CHECKRESPONSE']._serialized_start=177
  _globals['_CHECKRESPONSE']._serialized_end=240
  _globals['_TIMETABLECHECKER']._serialized_start=242
  _globals['_TIMETABLECHECKER']._serialized_end=332
# @@protoc_insertion_point(module_scope)
