classroom_image   = "augusto573/classroom-service:latest"
db_user           = "admin"
db_password       = "password123"
classroom_db_name = "classroom_db"
kafka_topic_audit = "audit.logs"
smtp_user     = "ramsesrov@gmail.com"
smtp_password = "izdm yuiv tado ebsi"
from_email    = "ramsesrov@gmail.com"
